### ISSUE TITLE
Can't Install Ext: Not Compatible with VSCode v1.90.0

### ISSUE THREAD

**Issue by ShunchiZhang** [mvsde/vscode-webc#1]
Can't install 'fynn.vscode-webc' extension through VSCode extension marketplace (Shift+Cmd+X).

It alerts:

> Can't install 'fynn.vscode-webc' extension because it is not compatible with the current version of Visual Studio Code (version 1.90.0).

VSCode version:

```
Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by mvsde** [comment]
Hey, thank you for checking out the extension.

Can you try updating VS Code to the latest 1.91.0 release? The extension should be installable then.
