### ISSUE TITLE
Conflict with VSCodeVim?

### ISSUE THREAD

**Issue by VAggrippino** [mvsde/vscode-webc#3]
If this is installed along with [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim), VSCode will get stuck with an "Activating Extensions" message in the status bar as described in VSCodeVim/Vim#3826 and VSCodeVim/Vim#8428.

**Comment by mvsde** [comment]
I wasn’t able to reproduce this issue when installing the Vim extension alongside the WebC extension.

I’m also not sure what could cause such a conflict. The WebC extension is not doing anything special beyond providing definitions, semantic tokens, and attributes for the HTML language service. This is all pretty basic VS Code API stuff other extensions do, too.

**Comment by VAggrippino** [comment]
... And now I can't reproduce it either...

Thank you very much for trying.

I _was_ able to reproduce it several times even after attempting to clear VSCode's cache / temporary files, uninstalling all other extensions besides VSCodeVim and your WebC extension and rebooting my computer a few times. That was all before I wrote [this post](https://github.com/VSCodeVim/Vim/issues/8428#issuecomment-2254329289) in the VSCodeVim issues.

Today I was trying to reproduce the problem for you in a screen recording. That's not an easy task on this 2014 model HP laptop. OBS just crashes immediately, but it seems that VLC is up to the task. Anyway, the problem just didn't happen today.

::sigh:: I seem to be a magnet for weird problems.

Thank you again for your time.
